// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20jAjE6ShMet4rPrFYm_M0BHMzGXmD1g',
    appId: '1:864355904753:web:6e439900e3224130bc0d50',
    messagingSenderId: '864355904753',
    projectId: 'myecommerce-df0a7',
    authDomain: 'myecommerce-df0a7.firebaseapp.com',
    storageBucket: 'myecommerce-df0a7.appspot.com',
    measurementId: 'G-S77MSEZHZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcROBqMDzZE4nTtSvRIfWJsryyFIlSMxw',
    appId: '1:864355904753:android:7000496c53f672d7bc0d50',
    messagingSenderId: '864355904753',
    projectId: 'myecommerce-df0a7',
    storageBucket: 'myecommerce-df0a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqg_3deD81NuoV4CI3AFBr1VlF4NMgviM',
    appId: '1:864355904753:ios:0f37cca6394069cebc0d50',
    messagingSenderId: '864355904753',
    projectId: 'myecommerce-df0a7',
    storageBucket: 'myecommerce-df0a7.appspot.com',
    iosBundleId: 'com.example.myEcommerceAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqg_3deD81NuoV4CI3AFBr1VlF4NMgviM',
    appId: '1:864355904753:ios:9e2a20ecd5ba7f8cbc0d50',
    messagingSenderId: '864355904753',
    projectId: 'myecommerce-df0a7',
    storageBucket: 'myecommerce-df0a7.appspot.com',
    iosBundleId: 'com.example.myEcommerceAdmin.RunnerTests',
  );
}
